
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = 'Adventure'

SCALING = 1
TILE_SCALING = 0.15

COIN_SCALING = 0.7
COIN_NUMBER = 10

PLAYER_MOVEMENT_SPEED = 5
PLAYER_JUMP_SPEED = 20

GRAVITY = 1

LEFT_VIEWPORT_MARGIN = 250
RIGHT_VIEWPORT_MARGIN = 250
BOTTOM_VIEWPORT_MARGIN = 50
TOP_VIEWPORT_MARGIN = 100

RESTART_GAME_BUTTON = "R"
